version: 2
jobs:
  build:
    steps:
       - checkout
       - run:
          name: install-npm-wee
          command: npm start
  test:
    steps:
      - run:
          name: test
          command: npm test
