version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      - image: circleci/node:4.8.2
      - image: mongo:3.4.4
    steps:
      - checkout
      - run:
          command: |
            npm install
            npm test
